//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirTicketDetail
    {
        public int DetailID { get; set; }
        public string TransactionCode { get; set; }
        public string NameofPerson { get; set; }
        public string AirlinesCode { get; set; }
        public string Route { get; set; }
        public string TicketNo { get; set; }
        public string SeatTypeCode { get; set; }
        public string ProviderCode { get; set; }
        public Nullable<System.DateTime> TravelDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public decimal BaseFare { get; set; }
        public decimal GovTax { get; set; }
        public decimal AIT { get; set; }
        public decimal Comission { get; set; }
        public decimal ServiceChargePercent { get; set; }
        public decimal ServiceChargeValue { get; set; }
        public decimal DiscountValue { get; set; }
        public decimal CardChargeAmount { get; set; }
        public decimal TotalPayableAmt { get; set; }
        public bool IsForward { get; set; }
        public decimal ChangePenalty { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public bool IsCancel { get; set; }
        public decimal CancellationCharge { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<decimal> ComissionChargePercent { get; set; }
        public Nullable<decimal> ProviderPenalty { get; set; }
    }
}
