//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.ClientModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClientBusinessEntities : DbContext
    {
        public ClientBusinessEntities()
            : base("name=ClientBusinessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Destination> Destinations { get; set; }
        public virtual DbSet<PaymentInfo> PaymentInfoes { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<TravelAirline> TravelAirlines { get; set; }
        public virtual DbSet<CardMaster> CardMasters { get; set; }
        public virtual DbSet<CardType> CardTypes { get; set; }
        public virtual DbSet<TopUpType> TopUpTypes { get; set; }
        public virtual DbSet<CustomerType> CustomerTypes { get; set; }
        public virtual DbSet<VisaType> VisaTypes { get; set; }
        public virtual DbSet<CurrencyConversationHistory> CurrencyConversationHistories { get; set; }
        public virtual DbSet<SeatType> SeatType { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<HotelType> HotelType { get; set; }
        public virtual DbSet<RoomType> RoomType { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<HolidayPackageDetail> HolidayPackageDetail { get; set; }
        public virtual DbSet<HolidayPackageMaster> HolidayPackageMaster { get; set; }
        public virtual DbSet<PackageDetail> PackageDetail { get; set; }
        public virtual DbSet<PackageMaster> PackageMaster { get; set; }
        public virtual DbSet<ProductService> ProductService { get; set; }
        public virtual DbSet<MRMaster> MRMaster { get; set; }
        public virtual DbSet<ClientAdvancePayment> ClientAdvancePayment { get; set; }
        public virtual DbSet<TopUp> TopUp { get; set; }
        public virtual DbSet<OnlineRegDetail> OnlineRegDetail { get; set; }
        public virtual DbSet<OnlineRegMaster> OnlineRegMaster { get; set; }
        public virtual DbSet<AirTicketDetail> AirTicketDetail { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<VisaDetail> VisaDetail { get; set; }
        public virtual DbSet<VisaMaster> VisaMaster { get; set; }
        public virtual DbSet<AirTicketMaster> AirTicketMaster { get; set; }
        public virtual DbSet<HotelBookMaster> HotelBookMaster { get; set; }
        public virtual DbSet<GroupTourMaster> GroupTourMaster { get; set; }
        public virtual DbSet<GroupTourCustomer> GroupTourCustomer { get; set; }
        public virtual DbSet<GroupTourMember> GroupTourMember { get; set; }
        public virtual DbSet<HotelBookDetail> HotelBookDetail { get; set; }
        public virtual DbSet<GroupTourDetails> GroupTourDetails { get; set; }
        public virtual DbSet<MRInvoiceDetail> MRInvoiceDetail { get; set; }
        public virtual DbSet<MRPaymentDetails> MRPaymentDetails { get; set; }
    }
}
