//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAdvancePayment
    {
        public int ID { get; set; }
        public string AdvanceCode { get; set; }
        public System.DateTime AdvanceDate { get; set; }
        public decimal Amount { get; set; }
        public string CompanyCode { get; set; }
        public string CustomerCode { get; set; }
        public string PaymentType { get; set; }
        public string BankCode { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ClearingDate { get; set; }
        public Nullable<bool> isClear { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool isActive { get; set; }
    }
}
