//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string CustomerTypeCode { get; set; }
        public string CustomerAddress { get; set; }
        public string MobileNo { get; set; }
        public string EmergencyNo { get; set; }
        public string ContactPersion { get; set; }
        public string Passport { get; set; }
        public string NID { get; set; }
        public string Email { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool isActive { get; set; }
    
        public virtual CustomerType CustomerType { get; set; }
    }
}
