//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupTourDetails
    {
        public int ID { get; set; }
        public string TransactionCode { get; set; }
        public string ServiceCode { get; set; }
        public string CustomerCode { get; set; }
        public string NameofParticipent { get; set; }
        public string ProviderCode { get; set; }
        public string AirlinesCode { get; set; }
        public string CountryCode { get; set; }
        public string Route { get; set; }
        public string HotelName { get; set; }
        public string RoomType { get; set; }
        public decimal CardChargeAmount { get; set; }
        public decimal MainPrice { get; set; }
        public decimal GovtTax { get; set; }
        public decimal Commision { get; set; }
        public decimal ServiceParcent { get; set; }
        public decimal ServiceCharge { get; set; }
        public decimal Discount { get; set; }
        public bool IsCancel { get; set; }
        public decimal CancelationCharge { get; set; }
        public decimal TotalPayableamt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
