//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayPackageDetail
    {
        public int ID { get; set; }
        public string HOPCode { get; set; }
        public string PackageCode { get; set; }
        public string EventName { get; set; }
        public string EventDetail { get; set; }
        public string EventRemark { get; set; }
        public Nullable<decimal> EventCharge { get; set; }
    }
}
