//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayPackageMaster
    {
        public int ID { get; set; }
        public string HOPCode { get; set; }
        public Nullable<System.DateTime> TourDate { get; set; }
        public Nullable<int> NoOfPersonAdult { get; set; }
        public Nullable<int> NoOfPersonChild { get; set; }
        public string CustomerCode { get; set; }
        public string CompanyCode { get; set; }
        public string Destination { get; set; }
        public string PackageCode { get; set; }
        public Nullable<int> NoOfDay { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> CurrencyRate { get; set; }
        public Nullable<decimal> TotalServiceCharge { get; set; }
        public Nullable<decimal> TotalPayable { get; set; }
        public string CardCode { get; set; }
        public string SalesStaffCode { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
