//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelBookMaster
    {
        public int ID { get; set; }
        public string TransactionCode { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string CustomerCode { get; set; }
        public string SalesStaffCode { get; set; }
        public string CardCode { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> CurrencyRate { get; set; }
        public string Remark { get; set; }
        public decimal NetPayableAmt { get; set; }
        public bool IsFinalLocked { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
