//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelBookDetail
    {
        public int DetailID { get; set; }
        public string TransactionCode { get; set; }
        public string NameofPerson { get; set; }
        public string CityName { get; set; }
        public string TravelProvider { get; set; }
        public string HotelName { get; set; }
        public string BookingRefNo { get; set; }
        public string RoomType { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<int> NoOfDay { get; set; }
        public Nullable<decimal> CardChargeAmount { get; set; }
        public decimal RoomFare { get; set; }
        public decimal ServiceChargePercent { get; set; }
        public decimal ServiceChargeValue { get; set; }
        public decimal DiscountValue { get; set; }
        public decimal TotalPayableAmt { get; set; }
        public bool IsCancel { get; set; }
        public decimal CancellationCharge { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
