//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRMaster
    {
        public int ID { get; set; }
        public string ReceiptCode { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public string CustomerCode { get; set; }
        public decimal TotalPayableAmount { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
