//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRPaymentDetails
    {
        public int ID { get; set; }
        public string ReceiptCode { get; set; }
        public string PaymentType { get; set; }
        public decimal ReceivedAmount { get; set; }
        public string BankName { get; set; }
        public string ChequeNo { get; set; }
        public string CardNo { get; set; }
        public string POSTransactionNo { get; set; }
        public string TxnNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string AdvanceCode { get; set; }
    }
}
