//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageDetail
    {
        public int ID { get; set; }
        public string PackageCode { get; set; }
        public string EventName { get; set; }
        public string EventDetails { get; set; }
        public Nullable<decimal> EventPrice { get; set; }
        public string Remarks { get; set; }
    }
}
