//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageMaster
    {
        public int ID { get; set; }
        public string PackageCode { get; set; }
        public string PackageName { get; set; }
        public string Summary { get; set; }
        public Nullable<int> NoOfDay { get; set; }
        public Nullable<int> NoOfNight { get; set; }
        public decimal TotalPackagePrice { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
