//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentInfo
    {
        public int ID { get; set; }
        public string PaymentCode { get; set; }
        public string PaymentType { get; set; }
        public string CardNo { get; set; }
        public string CardName { get; set; }
        public string TransactionNo { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Limit { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool isActive { get; set; }
    }
}
