//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopUp
    {
        public int ID { get; set; }
        public string TopUpCode { get; set; }
        public string TopUpTypeCode { get; set; }
        public string ProviderID { get; set; }
        public string CardID { get; set; }
        public string AirlinesID { get; set; }
        public Nullable<System.DateTime> TopUpDate { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool isActive { get; set; }
    }
}
