//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisaDetail
    {
        public int DetailID { get; set; }
        public string TransactionCode { get; set; }
        public string NameofPerson { get; set; }
        public string VisaType { get; set; }
        public string VisaCountry { get; set; }
        public string PassportNo { get; set; }
        public Nullable<decimal> CardChargeAmount { get; set; }
        public decimal VisaFee { get; set; }
        public decimal GovtTax { get; set; }
        public decimal ServiceChargePercent { get; set; }
        public decimal ServiceChargeValue { get; set; }
        public decimal TotalPayableAmt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string ProviderCode { get; set; }
    }
}
