//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.SysModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIRequestLog
    {
        public int ID { get; set; }
        public string APIURL { get; set; }
        public string EmployeeCode { get; set; }
        public System.DateTime RequestOn { get; set; }
    }
}
