//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.SysModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrowsingLog
    {
        public int ID { get; set; }
        public string EmployeeCode { get; set; }
        public int ApplicationID { get; set; }
        public string ApplicationVersion { get; set; }
        public int MenuID { get; set; }
        public System.DateTime RequestedOn { get; set; }
        public string Device { get; set; }
        public string DeviceType { get; set; }
        public string OS { get; set; }
        public string OSVersion { get; set; }
        public string BrowserName { get; set; }
        public string BrowserVersion { get; set; }
        public string UserAgent { get; set; }
        public string ISPName { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string CountryCode { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string RegionName { get; set; }
        public string TimeZone { get; set; }
        public string ZipCode { get; set; }
        public string Remark { get; set; }
    }
}
