//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.SysModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<int> EmployeeLocationID { get; set; }
        public Nullable<int> EmployeeTypeID { get; set; }
        public string FullName { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string BloodGroup { get; set; }
        public string Religion { get; set; }
        public string Sex { get; set; }
        public string MaritalStatus { get; set; }
        public string Telephone { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string NationalIDNo { get; set; }
        public string Nationality { get; set; }
        public string EPersonName { get; set; }
        public string EPersonAddress { get; set; }
        public string EPersonTelephone { get; set; }
        public Nullable<int> EmployeeStatusID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }
}
