//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.SysModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLocation
    {
        public int ID { get; set; }
        public string LocationCode { get; set; }
        public string LocationName { get; set; }
        public string ShortForm { get; set; }
        public string LocationAddress { get; set; }
        public Nullable<bool> IsMainBranch { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public byte[] BranchLogo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
