//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.SysModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ID { get; set; }
        public string EmployeeCode { get; set; }
        public string APIURL { get; set; }
        public string ErrorTitle { get; set; }
        public string ErrorDetail { get; set; }
        public bool IsSolved { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string SolvedBy { get; set; }
        public Nullable<System.DateTime> SolvedOn { get; set; }
    }
}
