//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.SysModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class signature
    {
        public int ID { get; set; }
        public string KeyID { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public int NoOfDigit { get; set; }
        public string DBName { get; set; }
        public string TableType { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string InitialCode { get; set; }
        public string CriteriaColumn { get; set; }
        public string ExtraCondition { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
