//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data.SysModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SysManageEntities : DbContext
    {
        public SysManageEntities()
            : base("name=SysManageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<EmployeeDepartment> EmployeeDepartments { get; set; }
        public virtual DbSet<EmployeeStatusTbl> EmployeeStatusTbls { get; set; }
        public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleAcessTbl> RoleAcessTbls { get; set; }
        public virtual DbSet<UserAccessTbl> UserAccessTbls { get; set; }
        public virtual DbSet<UserAccessType> UserAccessTypes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<APIRequestLog> APIRequestLogs { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<BrowsingLog> BrowsingLogs { get; set; }
        public virtual DbSet<EmployeeLocation> EmployeeLocations { get; set; }
        public virtual DbSet<EmployeeDesignation> EmployeeDesignations { get; set; }
        public virtual DbSet<CompanyProfile> CompanyProfiles { get; set; }
        public virtual DbSet<TableType> TableTypes { get; set; }
        public virtual DbSet<signature> signatures { get; set; }
        public virtual DbSet<UserTbl> UserTbls { get; set; }
    }
}
